# fly.toml app configuration file generated for ybedatop on 2023-11-26T03:23:51+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ybedatop"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
